### ISSUE TITLE
Wait Saving Not Going Away on Certain Save Events

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1345]
This seems to be the case when entering really long unbroken strings into the location ...

Screen shot below. I have also had this occur when removing an instructor from an offering.

![image](https://user-images.githubusercontent.com/7493331/79787963-b8156200-82fc-11ea-8605-a48c2477551c.png)

**Comment by jrjohnson** [comment]
This is happening when more than one offering is saved or the same offering is saved twice. I think it's a result of the `save.isRunning` task only completing after the component has been destroyed which leaves some content in the modal dialog. Since the dialog is moved outside the DOM flow be `ember-modal-dialog` it doesn't get cleaned up. When the next offering is edited the original `isRunning` state mixes in and shows the saving message.
