### ISSUE TITLE
Link Appears Active But Should Not Due to Date Restrictions

### ISSUE THREAD

**Issue by dartajax** [ilios/common#2240]
![image](https://user-images.githubusercontent.com/7493331/124324947-aa7e7d80-db38-11eb-8e0c-04438710db29.png)

You can click the link which may not take you anywhere. But it probably should not appear to be enabled if the date has been passed.

**Comment by stopfstedt** [comment]
ok, i chased this down. the account you're using to view this event must have permissions to  "view draft contents", which allows the display of timed materials outside their scheduling window. 
otherwise, you would see just the title of the otherwise blanked LM. no extra information about availability would be shown.
