### ISSUE TITLE
import ember-concurrency from simple-charts

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#634]
if possible.

we're getting dependency-linter warnings in frontend due to version mismatches with this library all the time.

**Comment by jrjohnson** [comment]
Instead I think we should just widen our range in both libraries and figure out how to keep it that way with dependabot.

**Comment by jrjohnson** [comment]
Ah, I see the issue is that `ember-concurrency` is pre-1.0 so a version constraint like `^0.8.0` doesn't allow a bump to `0.9.0`. I added some comments to their 1.0 tracker to maybe push a release sooner, but until then we're probably in trouble here. I don't mind relying on `simple-charts` to provide this package, I'm certain that if we remove it from there tests over here would break like crazy so it should be fine.
